# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_ussd', '0021_auto_20170101_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='direction',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Incoming'), (2, 'Outgoing')], null=True, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='from_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(39, '039 ==> Киевстар (Golden Telecom)'), (50, '050 ==> Vodafone'), (63, '063 ==> Life:)'), (66, '066 ==> Vodafone'), (67, '067 ==> Киевстар'), (68, '068 ==> Киевстар (Beeline)'), (91, '091 ==> Utel'), (92, '092 ==> PEOPLEnet'), (93, '093 ==> Life:)'), (94, '094 ==> Интертелеком'), (95, '095 ==> Vodafone'), (96, '096 ==> Киевстар'), (97, '097 ==> Киевстар'), (98, '098 ==> Киевстар'), (99, '099 ==> Vodafone')], null=True, verbose_name='Код провайдера'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='to_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(39, '039 ==> Киевстар (Golden Telecom)'), (50, '050 ==> Vodafone'), (63, '063 ==> Life:)'), (66, '066 ==> Vodafone'), (67, '067 ==> Киевстар'), (68, '068 ==> Киевстар (Beeline)'), (91, '091 ==> Utel'), (92, '092 ==> PEOPLEnet'), (93, '093 ==> Life:)'), (94, '094 ==> Интертелеком'), (95, '095 ==> Vodafone'), (96, '096 ==> Киевстар'), (97, '097 ==> Киевстар'), (98, '098 ==> Киевстар'), (99, '099 ==> Vodafone')], null=True, verbose_name='Код провайдера'),
        ),
        migrations.AlterField(
            model_name='ussd',
            name='direction',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Receive'), (2, 'Send')], null=True, verbose_name='Направление'),
        ),
    ]
