# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_ussd', '0022_auto_20170607_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sim',
            name='imsi',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='IMSI'),
        ),
    ]
