# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms_ussd', '0023_auto_20170625_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='id',
        ),
    ]
