"""
Django settings for Callbox project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from kombu import Queue, Exchange

DB_URL = ''
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zjkd(t^os%!li3vudp@^@!y(1=wry=_xvxcd(n03v4qvvy_x70'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'med.callbox.biz', ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    'monitor',
    'registration',
    'callcenter',
    'cc_stat',
    'agentstat',
    'stats_by_company',
    'events',
    'reports'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware'
]

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_SAVE_EVERY_REQUEST = False

REDIS_LOCATION = 'redis://127.0.0.1:6379/'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_LOCATION,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
    }
}

ROOT_URLCONF = 'Callbox.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR+"/templates", ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'monitor.context_processor.get_queue',

            ],
        },
    },
]

WSGI_APPLICATION = 'Callbox.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'asterisk',
        'USER': 'asterisk',
        'PASSWORD': '2f6fc7ccb9b5af56bcf1',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    },
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_L10N = False

USE_TZ = False

DATE_FORMAT = 'd-m-Y'
DATE_INPUT_FORMAT = ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%d-%m-%Y']
TIME_FORMAT = 'H:i:s'
TIME_INPUT_FORMAT = ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']
DATETIME_FORMAT = '%s %s' % (DATE_FORMAT, TIME_FORMAT)
DATETIME_INPUT_FORMATS = [
    '%s %s' % (date_format, time_format)
    for date_format in DATE_INPUT_FORMAT
    for time_format in TIME_INPUT_FORMAT
]

MEDIA_URL = '/media/'

MEDIA_ROOT = (os.path.join(BASE_DIR, 'media'))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/var/www/Callbox/static/'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/registration/login/'

CACHE_TIME_FOR_CALLCENTER = 30

CELERY_QUEUES = (
    Queue('normal', Exchange('normal'), routing_key='normal'),
    Queue('events', Exchange('events'), routing_key='events'),
)

CELERY_DEFAULT_QUEUE = 'normal'
CELERY_DEFAULT_EXCHANGE = 'normal'
CELERY_DEFAULT_ROUTING_KEY = 'normal'

CELERY_IMPORTS = ('events.tasks', )

CELERY_ALWAYS_EAGER = True

# reports
EMAIL_HOST = 'mail.index3.ru'
EMAIL_PORT = 587
EMAIL_SUBJECT = 'Report'
EMAIL_TEXT = 'Month report'
EMAIL_HOST_USER = 'tech@callbox.biz'
EMAIL_HOST_PASSWORD = 'd3df5f9d2813b30ad6bf'
RECIPIENTS = ['avgoeid@gmail.com']
REPORT_TIME = '17:02:00'
REPORT_DAY = 5

# an asterisk monitoring
AS_MANAGER_IP = '88.99.101.29'
AS_MANAGER_LOGIN = 'www-admin'
AS_MANAGER_PASSWORD = '0df07d804c8679555826'

MONITORING_KEY = 'monitoring'
MONITOR_CHANNELS_CONCISE = ('core show channels concise', 'channels_concise')
MONITOR_QUEUES_SHOW = ('queue show', 'queues_show')

try:
    from local_settings import *
except ImportError:
    pass

if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']
    MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
    INTERNAL_IPS = ('127.0.0.1',)
