# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sessionid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='SessionID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='topic',
            field=models.CharField(default='', max_length=256, verbose_name='Тема курса'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(default='', max_length=256, verbose_name='Раздел мероприятия'),
        ),
    ]
