# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0004_auto_20160729_1238'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='slide',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='slide',
            name='opening_method',
            field=models.PositiveSmallIntegerField(choices=[(1, '_blank'), (2, '_self')], default=1, verbose_name='Метод открытия страницы слайда'),
        ),
    ]
