# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 10:58
from __future__ import unicode_literals

import applications.slide.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0005_auto_20170607_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3')], default=1, verbose_name='Тип рекламы')),
                ('type_1_first_number', models.CharField(default='6', max_length=6, verbose_name='Первая линия цифры')),
                ('type_1_first_chars', models.CharField(default='ШТ', max_length=6, verbose_name='Первая линия буквы')),
                ('type_1_second_number', models.CharField(default='20', max_length=6, verbose_name='Вторая линия цифры')),
                ('type_1_third_chars', models.CharField(default='На стаканчики десертные', max_length=128, verbose_name='Третья линия буквы')),
                ('type_1_fourth_chars', models.CharField(default='ПИРАМИДА', max_length=128, verbose_name='Четвертая линия буквы')),
                ('type_1_fifth_slug', models.CharField(default='#', max_length=256, verbose_name='Пятая линия адрес')),
                ('img', models.ImageField(blank=True, help_text='Ориентировочно: - Type 1: Высота: 147 x Ширина: 197\n - Type 2: Высота: 169 x Ширина: 219\n - Type 3: Высота: 136 x Ширина: 151\n', null=True, upload_to=applications.slide.models.set_path_image, verbose_name='Картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
