# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0006_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='img_alt',
            field=models.CharField(default='Предложение интернет-магазина Кексик', help_text='Описание картинки для поисковых систем.', max_length=256, verbose_name='ALT Картинки'),
        ),
    ]
