# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 14:50
from __future__ import unicode_literals

import applications.slide.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slide', '0007_recommend_img_alt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommend',
            options={'ordering': ['updated_at'], 'verbose_name': 'Реккомендация', 'verbose_name_plural': 'Реккомендации'},
        ),
        migrations.RenameField(
            model_name='recommend',
            old_name='type_1_first_number',
            new_name='type_1_first_numbers',
        ),
        migrations.RenameField(
            model_name='recommend',
            old_name='type_1_second_number',
            new_name='type_1_second_numbers',
        ),
        migrations.AddField(
            model_name='recommend',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Если мы хотим чтобы не показывался, ставим данное поле в False.', verbose_name='Актив. или Пасив'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_2_first_chars',
            field=models.CharField(default='грн.', max_length=6, verbose_name='Первая линия буквы'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_2_first_number',
            field=models.CharField(default='65', max_length=6, verbose_name='Первая линия цифры'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_2_fourth_slug',
            field=models.CharField(default='#', max_length=256, verbose_name='Четвертая линия адрес'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_2_second_chars',
            field=models.CharField(default='Мастика Criamo универсальная Розовая', max_length=128, verbose_name='Вторая линия буквы'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_2_third_chars',
            field=models.CharField(default='кг.', max_length=6, verbose_name='Третья линия буквы'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_2_third_numbers',
            field=models.CharField(default='0,5', max_length=6, verbose_name='Третья линия цифры'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_3_first_title',
            field=models.CharField(default='Форма Сердце', max_length=64, verbose_name='Первая линия буквы'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_3_quantity',
            field=models.CharField(default='3', max_length=6, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_3_second_list_first_line',
            field=models.CharField(default='Силикон', max_length=32, verbose_name='Вторая линия, первая линия списка'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_3_second_list_second_line',
            field=models.CharField(default='18 см; высота 3 см.', max_length=32, verbose_name='Вторая линия, вторая линия списка'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_3_third_chars',
            field=models.CharField(default='штука', max_length=6, verbose_name='Третья линия буквы (еденицы измерения)'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_3_third_price',
            field=models.CharField(default='127', max_length=6, verbose_name='Третья линия цифры (Цена, грн)'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='type_3_third_price_broken_money',
            field=models.CharField(default='99', max_length=6, verbose_name='Третья линия цифры (Цена, коп)'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='img',
            field=models.ImageField(blank=True, help_text='Ориентировочно: - Type 1: Высота: 147 x Ширина: 197\n - Type 2: Высота: 169 x Ширина: 219\n - Type 3: Высота: 136 x Ширина: 151\n - Type 4 (Banner): Высота: 175 x Ширина: 962\n', null=True, upload_to=applications.slide.models.set_path_image, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3'), (4, 'Type 4 (Banner)')], default=1, verbose_name='Тип рекламы'),
        ),
        migrations.AlterModelTable(
            name='recommend',
            table='Recommend',
        ),
    ]
