# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20170112_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='custom_sum',
            field=models.BooleanField(default=False, verbose_name='Сумма заказа введена в ручную'),
        ),
    ]
