# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0086_auto_20161206_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='href',
            field=models.CharField(default='http://keksik.com.ua/', max_length=256, verbose_name='URL'),
        ),
    ]
