# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery2', '0011_delivery_is_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='is_system',
        ),
    ]
