# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20170530_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_code_ISO_char',
            field=models.CharField(default='UAH', max_length=3, verbose_name='Код валюты буквенный'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='Наименование производителя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='action',
            field=models.ManyToManyField(blank=True, db_table='Product_to_Action', related_name='product_in_action', to='discount.Action', verbose_name='Акции'),
        ),
        migrations.AlterField(
            model_name='viewed',
            name='last_viewed',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата последнего просмотра'),
        ),
    ]
