# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20170626_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='serial_number',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, default=1, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
