# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20170626_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Заголовок категории'),
        ),
    ]
