# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20170626_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='action',
            field=models.ManyToManyField(blank=True, db_table='Product_to_Action', related_name='product_in_action', to='discount.Action', verbose_name='Акции'),
        ),
    ]
