# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_auto_20170626_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_main_page',
            field=models.BooleanField(db_index=True, default=False, help_text='Если мы хотим чтобы продукт показывался на главной странице ставим данное поле в True.', verbose_name='На главной странице'),
        ),
        migrations.AlterField(
            model_name='viewed',
            name='last_viewed',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата последнего просмотра'),
        ),
        migrations.AlterField(
            model_name='viewed',
            name='sessionid',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='SessionID'),
        ),
    ]
