# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20170626_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='google_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Google. Дата и время последней проверки'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_google',
            field=models.NullBooleanField(verbose_name='Google. В индексе'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_yandex',
            field=models.NullBooleanField(verbose_name='Yandex. В индексе'),
        ),
        migrations.AddField(
            model_name='product',
            name='yandex_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yandex. Дата и время последней проверки'),
        ),
    ]
