# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_auto_20170702_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttocategory',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная категория'),
        ),
    ]
