# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 14:58
from __future__ import unicode_literals

import applications.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_category_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='billboard_img',
            field=models.ImageField(blank=True, help_text='Сюда добавляем картинку от 1920 px ширина и от 174 px высота', null=True, upload_to=applications.product.models.set_path_image, verbose_name='Биллбоард'),
        ),
        migrations.AddField(
            model_name='category',
            name='billboard_img_alt',
            field=models.CharField(blank=True, help_text='Описание Биллбоарда для поисковых систем от 6 до 10 слов', max_length=128, null=True, verbose_name='Alt Биллбоарда'),
        ),
    ]
