# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20171030_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_left_vertical_column',
            field=models.BooleanField(default=False, help_text='Если мы хотим чтобы категория показываласьв левой колонке ставим данное поле в True.', verbose_name='Левая вертикальная колонка'),
        ),
        migrations.AddField(
            model_name='category',
            name='serial_number_first_column',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Порядковый номер в нижней части сайта в первой колонке.', null=True, verbose_name='Первая колонка'),
        ),
        migrations.AddField(
            model_name='category',
            name='serial_number_fourth_column',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Порядковый номер в нижней части сайта в четвертой колонке.', null=True, verbose_name='Четвертая колонка'),
        ),
        migrations.AddField(
            model_name='category',
            name='serial_number_second_column',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Порядковый номер в нижней части сайта во второй колонке.', null=True, verbose_name='Вторая колонка'),
        ),
        migrations.AddField(
            model_name='category',
            name='serial_number_third_column',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Порядковый номер в нижней части сайта в третьей колонке.', null=True, verbose_name='Третья колонка'),
        ),
    ]
