# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Наименование настройки'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='variable_name',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='Имя переменной'),
        ),
    ]
