# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20160327_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'comment'), (1, 'opinion')], null=True),
        ),
    ]
