# -*- coding: utf-8 -*-

CML_APP = 'bitrix'

CML_BITRIX_AUTH_UNAME = 'User123'
CML_BITRIX_AUTH_PASSWD = 'password123'

CML_RESPONSE_SUCCESS = 'success'
CML_RESPONSE_PROGRESS = 'progress'
CML_RESPONSE_ERROR = 'failure'

CML_USE_ZIP = False
CML_FILE_LIMIT = 0

CML_UPLOAD_ROOT = 'storage'

CML_DELETE_FILES_AFTER_IMPORT = False
