# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authModel', '0010_auto_20170607_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
