# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 14:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authModel', '0011_remove_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_parent_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
